config/routes.rb
Board::Application.routes.draw do
  match 'users/new' => 'users#new', :as => "new_user"
  match 'users/:uuid/messages' => 'users#messages'
  match 'users/:uuid/message_keys' => 'users#message_keys'
  match 'users/:uuid' => 'users#show', :as => "users_uuid"
  match 'users' => 'users#index', :via => :get, :as => "users"
  match 'users' => 'users#create', :via => :post, :as => "users"

  match 'messages/new' => 'messages#new', :as => "new_message"
  match 'messages' => 'messages#index', :via => :get, :as => "messages"
  match 'messages' => 'messages#create', :via => :post, :as => "messages"

  match '/' => 'users#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  has_many 	:message_keys
  has_many	:users, :through => :message_keys
  belongs_to	:user
  alias_attribute	:sender, :user
end

app/models/message_key.rb
class MessageKey < ActiveRecord::Base
  belongs_to	:message
  belongs_to	:user
  alias_attribute	:recipient, :user

  def details
	{ :message => message, :sender => message.sender, :recipient => recipient }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many      :message_keys
  has_many      :messages, :through => :message_keys

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages, :include => [:user] }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message, :include => [:user] }
      format.js { }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new
    @recipient = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
      format.js { }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    @sender = User.find(:first, :conditions => [ "uuid = ?", params[:sender_uuid]])
    @message.user_id = @sender.id
    @message.save
    
    if params[:recipients].is_a?(String)
      recipient_keys = params[:recipients].split(':uuid:')
      
      recipient_keys.each do |key|
        recipient_key = key.split(':key:')

        @recipient = User.find(:first, :conditions => [ "uuid = ?", recipient_key[0]])
    
        @message_key = MessageKey.new
        @message_key.message_id = @message.id;
        @message_key.user_id = @recipient.id
        @message_key.encrypted_key = recipient_key[1] 
        @message_key.save
      end
    end

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
        format.js { }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
        format.js { }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def messages
    @user = User.find(:first, :conditions => [ "uuid = ?", params[:uuid]])
    @messages = @user.messages

    respond_to do |format|
      format.json { render :json => @messages.to_json(:include => [:sender]) }
    end
  end

  def message_keys
    @user = User.find(:first, :conditions => [ "uuid = ?", params[:uuid]])
    @message_keys = @user.message_keys

    respond_to do |format|
      format.json { render :json => @message_keys, :methods => :details }
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/uuid
  # GET /users/uuid.json
  def show
    @users = User.all
    @user = User.find(:first, :conditions => [ "uuid = ?", params[:uuid]])
    @message = Message.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(:first, :conditions => [ "uuid = ?", params[:uuid]])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.uuid = UUIDTools::UUID.random_create.to_s

    respond_to do |format|
      if @user.save
        format.html { redirect_to @users, notice: 'User was successfully created.' }
        format.json { render json: @users, status: :created, location: @user }
	format.js { }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(:first, :conditions => [ "uuid = ?", params[:uuid]])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Board</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<div id="message" style="clear:left;position:relative">

	<select name="users" id="users" size="4" multiple="multiple">
		<% @users.each do |user| %>
		<option><%= user.uuid %></option>
		<% end %>
	</select>

	<div class="field">
		<label for="recipient_uuid_input">recipient uuid</label>
		<br />
		<input id="recipient_uuid_input" type="text" class="recipient" />
		<br />
		<a href="#" id="add_recipient">Add Recipient</a>
	</div>

	<div class="field">
		<label for="message_input">message</label>
		<br />
		<textarea cols="40" id="message_input" />
		</textarea>
	</div>

	<%= form_for(@message, :remote => true) do |f| %>
	<% if @message.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

		<ul>
			<% @message.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<%= hidden_field_tag "sender_uuid" %>

	<%= hidden_field_tag "recipients" %>

	<%= f.hidden_field :body %>

	<%= f.hidden_field :signature %>
	<div class="actions">
		<%= f.submit %>
	</div>
	<% end %>
</div>

app/views/messages/_new_js.html.erb
jQuery(function($) {
	var vc = new view_controller()

	$(window).bind('mousemove', vc.collect)
	sjcl.random.startCollectors()

	$("button").button()
	$("#add_recipient").bind('click', vc.add_recipient)
	
	$("#new_message").bind('submit', function(event) {
		return vc.send_message(event)
	})
	$("#entropy").progressbar({
		value : 0
	})
	$("#message").hide()
	$("#sender_information").hide()
	$("#instruction").text("move your mouse to generate entropy")
})
function view_controller() {
	"use strict"

	if(!(this instanceof view_controller))
		throw new Error("Constructor called as a function")

	var vc = this

	this.crypto = new crypto()

	this.collect = function() {
		var progress = sjcl.random.getProgress(10)

		if(progress === undefined || progress == 1) {
			sjcl.random.stopCollectors()
			$(window).unbind('mousemove', vc.collect)
			$("#entropy").hide()
			$("#message").show()
			$("#sender_information").show()
			$("#instruction").text("")
		} else {
			var percentage = progress * 100;
			$("#entropy").progressbar({
				value : percentage
			})
		}
	}
	
	this.add_recipient = function(event) {
		var recipient_num = $(".recipient").length
		var next = new Number(recipient_num + 1)
		
		var new_recipient_input = $("#recipient_uuid_input").clone().attr("id", "recipient_uuid_input_" + next)	
		$("#recipient_uuid_input").after(new_recipient_input)
	}

	this.send_message = function(event) {
		if(!$("#passphrase").val() || !$("#sender_uuid_input").val() || !$("#recipient_uuid_input").val() || !$("#message_input").val()) {

			console.log("invalid argument(s)")
			event.preventDefault()
			return false
		}

		var sender = $("#sender_uuid_input").val().trim()
		var recipients = [sender]

		$(".recipient").each(function(index) {
			recipients.push($(this).val().trim())
		})
		
		var message = $("#message_input").val()
		var passphrase = $("#passphrase").val()

		var prepared_message = this.crypto.prepare_message(sender, recipients, passphrase, message)

		for(var i = 0; i < recipients.length; i++) {
			if($("#recipients").val()) {
				$("#recipients").val($("#recipients").val() + ":uuid:")
			}
			
			var recipient = recipients[i]
			$("#recipients").val($("#recipients").val() + recipient + ":key:" + prepared_message.encrypted_message_keys[recipient])	
		}
		
		$("#sender_uuid").val(sender)
		
		$("#message_body").val(prepared_message.encrypted_message)
		$("#message_signature").val(prepared_message.signature)

		return true
	}
}

app/views/messages/create.js.erb
alert('created');

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Signature</th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.body %></td>
    <td><%= message.signature %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<% content_for :head do %>
<script type="text/javascript"><%= render :partial => "new_js" %></script>
<% end %>

<h3>create new message</h3>

<div style="clear:left;position:relative">
	<span id="instruction"></span>
</div>

<div id="entropy" style="float:left;position:relative;width:200px;max-height:20px"></div>

<div id="sender_information">
	<div class="field">
		<label for="passphrase">sender passphrase</label>
		<br />
		<input id="passphrase" type="text" />
	</div>

	<div class="field">
		<label for="sender_uuid_input">sender uuid</label>
		<br />
		<input id="sender_uuid_input" type="text" />
	</div>
</div>

<%= render 'form' %>

<div>
	<span id="notice"></span>
</div>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @message.body %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/_form.html.erb
<div id="entropy" style="float:left;position:relative;width:200px;max-height:20px"></div>

<div id="passphrase-div" style="clear:left;position:relative;width:198px">
  <input id="passphrase" type="text" style="width:100%;border:1px solid #000;background:#e1e1e1;padding:1px" />
  <%= link_to 'Create', '#', :id => 'create-user' %>
</div>

<div id="submission" style="clear:left;position:relative">
<%= form_for(@user, :url => users_path, :remote => true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :encrypted_private_key %>
  <%= f.hidden_field :public_key %>
  <%= f.hidden_field :encrypted_signing_key %>
  <%= f.hidden_field :verification_key %>
<% end %>
</div>

app/views/users/_new_js.html.erb
jQuery(function($) {
	var vc = new view_controller()

	$(window).bind('mousemove', vc.collect)
	sjcl.random.startCollectors()

	$("#new_user").bind('submit', function(event) {
		return vc.place_keys(event)
	})
	$("#entropy").progressbar({
		value : 0
	})
	$("#passphrase-div").hide()
	$("#submission").hide()
	$("#instruction").text("move your mouse to generate entropy")
	$("#create-user").bind('click', function() {
		$("#new_user").submit()
	})
})
function view_controller() {"use strict"

	if(!(this instanceof view_controller))
		throw new Error("Constructor called as a function")

	var vc = this

	this.crypto = new crypto()
	this.keys = {}

	this.collect = function() {
		var progress = sjcl.random.getProgress(10)

		if(progress === undefined || progress == 1) {
			$("#entropy").progressbar({
				value : 100
			})
			sjcl.random.stopCollectors()
			$(window).unbind('mousemove', vc.collect)
			vc.keys = vc.crypto.generate_keys()
			$("#submission").show()
			$("#passphrase-div").show()
			$("#entropy").hide()
			$("#passphrase").focus()
			$("#instruction").text("enter a passphrase")
		} else {
			var percentage = progress * 100;
			$("#entropy").progressbar({
				value : percentage
			})
		}
	}

	this.place_keys = function(event) {
		if(!$("#passphrase").val() || !vc.keys) {
			console.log("passphrase and full entropy are required")
			event.preventDefault()
			return false
		}

		$("#create-user").unbind('click', function() {
			$("#new_user").submit()
		})

		vc.keys = vc.crypto.encrypt_keys($("#passphrase").val(), vc.keys)

		$("#user_encrypted_private_key").val(vc.keys.encryption.sec)
		$("#user_public_key").val(JSON.stringify(vc.keys.encryption.pub))
		$("#user_encrypted_signing_key").val(vc.keys.signing.sec)
		$("#user_verification_key").val(JSON.stringify(vc.keys.signing.pub))

		return true
	}
}

app/views/users/_show_js.html.erb
jQuery(function($) {
	var vc = new view_controller()

	$(window).bind('mousemove', vc.collect)
	sjcl.random.startCollectors()
	
	$("#retrieve").bind('click', vc.retrieve_messages)
	
	$("#add_recipient").bind('click', vc.add_recipient)
	
	$("#entropy").progressbar({
		value : 0
	})
	
	$("#new_message").bind('submit', function(event) {
		return vc.send_message(event)
	})
})

function view_controller() {
	"use strict"

	if(!(this instanceof view_controller))
		throw new Error("Constructor called as a function")

	var vc = this

	this.crypto = new crypto()
	
	this.add_recipient = function(event) {
		var recipient_num = $(".recipient").length
		var next = new Number(recipient_num + 1)
		
		var new_recipient_input = $("#recipient_uuid_input").clone().attr("id", "recipient_uuid_input_" + next)	
		$("#recipient_uuid_input").after(new_recipient_input)
	}
	
	this.collect = function() {
		var progress = sjcl.random.getProgress(10)

		if(progress === undefined || progress == 1) {
			sjcl.random.stopCollectors()
			$(window).unbind('mousemove', vc.collect)
			$("#entropy").hide()
			$("#entropy_label").hide()
			$("#message").show()
			$("#sender_information").show()
			$("#instruction").text("")
		} else {
			var percentage = progress * 100;
			$("#entropy").progressbar({
				value : percentage
			})
		}
	}

	this.send_message = function(event) {
		if(!$("#passphrase").val() || !$("#user_uuid").text() || !$("#recipient_uuid_input").val() || !$("#message_input").val()) {

			console.log("invalid argument(s)")
			event.preventDefault()
			return false
		}

		var sender = $("#user_uuid").text().trim()
		var recipients = [sender]

		$(".recipient").each(function(index) {
			recipients.push($(this).val().trim())
		})
		
		var message = $("#message_input").val()
		var passphrase = $("#passphrase").val()

		var prepared_message = this.crypto.prepare_message(sender, recipients, passphrase, message)

		for(var i = 0; i < recipients.length; i++) {
			if($("#recipients").val()) {
				$("#recipients").val($("#recipients").val() + ":uuid:")
			}
			
			var recipient = recipients[i]
			$("#recipients").val($("#recipients").val() + recipient + ":key:" + prepared_message.encrypted_message_keys[recipient])	
		}
		
		$("#sender_uuid").val(sender)
		
		$("#message_body").val(prepared_message.encrypted_message)
		$("#message_signature").val(prepared_message.signature)

		return true
	}
	
	this.retrieve_messages = function() {
		var passphrase = $("#passphrase").val()

		if(!passphrase) {
			alert("Specify a passphrase!")
			return
		}

		var message_keys

		$.ajax({
			url : "/users/" + $("#user_uuid").text() + "/message_keys.json",
			dataType : "json",
			success : function(data) {
				message_keys = data
				try {
					vc.crypto.decrypt_messages(passphrase, message_keys)
				} catch(e) {
					alert("incorrect passphrase")
					return
				}
				vc.crypto.verify_messages(message_keys)
				vc.place_messages(message_keys)
			}
		})
	}

	this.place_messages = function(message_keys) {
		if(!message_keys)
			throw new Error("Invalid argument")

		for(var i = 0; i < message_keys.length; i++) {
			$("#messages").append("<tr>" + "<td><span>" + message_keys[i].details.sender.uuid + "</span></td>" + "<td><span>" + message_keys[i].details.message.body + "</span></td>")
		}
	}
}

app/views/users/create.js.erb
$('#notice').html('uuid successfully created: <%= @user.uuid %>')
$('#passphrase-div').hide()
$('#instruction').hide()

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', users_uuid_path(@user.uuid) %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Uuid</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.uuid %></td>
    <td><%= link_to 'Show', users_uuid_path(user.uuid)  %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    <%= render :partial => "new_js" %>
  </script>
<% end %>

<h3>create new user</h3>

<div style="clear:left;position:relative">
  <span id="instruction"></span>
</div>

<%= render 'form' %>

<div style="clear:left;position:relative">
  <span id="notice"></span>
</div>

app/views/users/show.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    <%= render :partial => "show_js" %>
  </script>
<% end %>

<h3>user information</h3>

<p id="notice"><%= notice %></p>

<p>
  <b>UUID:</b>
  <span id="user_uuid"><%= @user.uuid %></span>
</p>

<div>
  <label for="passphrase">Passphrase</label>
  <input type="text" id="passphrase" size="30" />
  <%= link_to 'Retrieve Messages', '#', :id => 'retrieve' %>
</div>

<hr />

<h3>messages for this user</h3>

<table>
  <thead>
    <tr>
      <th>sender</th>
      <th>message</th>
    </tr>
  </thead>
  <tbody id="messages"></tbody>
</table>

<hr />

<h3>create new message</h3>

<div id="entropy_label"><span>move mouse to generate entropy<br />this is necessary to generate keys for new messages</span></div>
<div id="entropy" style="float:left;position:relative;width:200px;max-height:20px"></div>

<%= render "messages/form" %>

<%= link_to 'Back', users_path %>